language: cpp

compiler:
  - clang

before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)' || {
      echo "Only docs were updated, stopping build process."
      exit
    }
  - sudo add-apt-repository -y ppa:h-rayflood/llvm;

  - sudo apt-get update -qq

  - wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-0.46/openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz
  - tar xvf openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz
  - git clone https://github.com/graalvm/mx.git

install:
  - sudo apt-get install --allow-unauthenticated -qq clang-3.9;
  - export CXX="clang++-3.9";

before_script:
  - export JAVA_HOME=$TRAVIS_BUILD_DIR/openjdk1.8.0_172-jvmci-0.46
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/mx

script:
  - mx sforceimports
  - mx build
  - mx test-all
  - cp snapshot/nodeprof.jar build/
  - mx test-all
